name: Build & Compile

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: 🧩 Build Extension
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ⚙️ Install Dependencies
        run: npm install

      - name: 🧱 Compile TypeScript
        run: npm run compile

      - name: ✅ Lint Code
        run: npm run lint || echo "Lint warnings ignored"

      - name: 🧪 Run Tests
        run: npm test || echo "No tests found"

      - name: 📤 Upload Build Output
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: compiled-extension
          path: out/
